(function(){window.IOL={Control:{},Handler:{}};var touch_events=["touchstart","touchmove","touchend","touchcancel"];var gesture_events=["gesturechange","gesturestart","gestureend"];var events=touch_events.concat(gesture_events);for(var i=0;i<events.length;i++){OpenLayers.Events.prototype.BROWSER_EVENTS.push(events[i]);OpenLayers.Map.prototype.EVENT_TYPES.push(events[i]);}
var getMousePosition=OpenLayers.Events.prototype.getMousePosition;OpenLayers.Events.prototype._old_getMousePosition=getMousePosition;OpenLayers.Events.prototype.getMousePosition=function(evt){if(touch_events.indexOf(evt.type)>-1){if(evt.touches.length==1){evt.clientX=evt.touches[0].clientX;evt.clientY=evt.touches[0].clientY;}}
return this._old_getMousePosition(evt);};IOL.isinstance=function(instance,klass){if(instance.CLASS_NAME==klass.prototype.CLASS_NAME){return true;}
return false;};IOL.doubletap_factory=function(callback,options){var doubletap_timer=null;var in_doubletap=null;var tap1=null;var timeout=500;return function(evt,addargs){if(evt.touches.length==1){if(!doubletap_timer){function setTap(){in_doubletap=false;doubletap_timer=false;}
doubletap_timer=setTimeout(setTap,timeout);}
if(!in_doubletap){tap1=evt.xy;in_doubletap=true;}else{var args=[evt,tap1].concat(addargs);args=args.concat(options);callback.apply(callback,args);}}};};IOL.fireMouseEvent=function(type,target,redispatchTouch){var newEvent=document.createEvent("MouseEvent");var screenX=0;var screenY=0;var clientX=0;var clientY=0;if(redispatch!=null){screenX=redispatchTouch.screenX;screenY=redispatchTouch.screenY;clientX=redispatchTouch.clientX;clientY=redispatchTouch.clientY;}
newEvent.initMouseEvent(type,true,true,window,1,screenX,screenY,clientX,clientY,false,false,false,false,0,null);target.dispatchEvent(newEvent);};})();IOL.Control.Panel=OpenLayers.Class(OpenLayers.Control.Panel,{ignore:"touchstart",timeout:500,doubletap_timer:false,in_doubletap:false,addControls:function(controls){var obj=this;if(!(controls instanceof Array)){controls=[controls];}
this.controls=this.controls.concat(controls);var _handler=IOL.doubletap_factory(function(evt,tap,ctrl){obj.activateControl(ctrl);});function taphandler(ctrl,evt){OpenLayers.Event.stop(evt?evt:window.event);_handler(evt,[ctrl]);};for(var i=0,len=controls.length;i<len;i++){var element=document.createElement("div");var textNode=document.createTextNode(" ");controls[i].panel_div=element;if(controls[i].title!=""){controls[i].panel_div.title=controls[i].title;}
OpenLayers.Event.observe(controls[i].panel_div,"touchstart",OpenLayers.Function.bind(taphandler,this,controls[i]));OpenLayers.Event.observe(controls[i].panel_div,this.ignore,OpenLayers.Function.bindAsEventListener(OpenLayers.Event.stop));}
if(this.map){for(var i=0,len=controls.length;i<len;i++){this.map.addControl(controls[i]);controls[i].deactivate();controls[i].events.on({"activate":this.redraw,"deactivate":this.redraw,scope:this});}
this.redraw();}},CLASS_NAME:"IOL.Control.Panel"});IOL.Handler.Drag=OpenLayers.Class(OpenLayers.Handler.Drag,{touchstart:function(evt){this.dragging=false;this.started=true;this.start=evt.xy;this.last=evt.xy;this.map.div.style.cursor="move";this.down(evt);this.callback("down",[evt.xy]);OpenLayers.Event.stop(evt);if(!this.oldOnselectstart){this.oldOnselectstart=(document.onselectstart)?document.onselectstart:function(){return true;};document.onselectstart=function(){return false;};}
return!this.stopDown;},touchmove:function(evt){if(this.started&&!this.timeoutId&&(evt.xy.x!=this.last.x||evt.xy.y!=this.last.y)){if(this.interval>0){this.timeoutId=setTimeout(OpenLayers.Function.bind(this.removeTimeout,this),this.interval);}
this.dragging=true;this.move(evt);this.callback("move",[evt.xy]);if(!this.oldOnselectstart){this.oldOnselectstart=document.onselectstart;document.onselectstart=function(){return false;};}
this.last=this.evt.xy;OpenLayers.Event.stop(evt);}
return true;},touchend:function(evt){if(this.started){var dragged=(this.start!=this.last);this.started=false;this.dragging=false;this.map.div.style.cursor="";this.up(evt);this.callback("up",[evt.xy]);if(dragged){this.callback("done",[evt.xy]);}
document.onselectstart=this.oldOnselectstart;}
return true;},CLASS_NAME:"IOL.Handler.Drag"});IOL.Control.DragPan=OpenLayers.Class(OpenLayers.Control.DragPan,{handlerClass:IOL.Handler.Drag,draw:function(){this.handler=new this.handlerClass(this,{"move":this.panMap,"done":this.panMapDone},{interval:this.interval});},initialize:function(options){OpenLayers.Control.DragPan.prototype.initialize.apply(this,arguments);},CLASS_NAME:"IOL.Control.DragPan"});IOL.Handler.DoubleTap=OpenLayers.Class(OpenLayers.Handler,{timeout:500,doubletap_timer:false,in_doubletap:false,tap1:null,tap2:null,touchmove:function(evt){if(this.in_doubletap==true){this.in_doubletap=false;this.doubletap_timer=false;this.tap1=null;this.tap2=null;}},touchstart:function(evt){evt.preventDefault();var timeout=this.timeout;if(event.touches.length==1){if(!this.doubletap_timer){var obj=this;function setTap(){this.in_doubletap=false;this.doubletap_timer=false;}
this.doubletap_timer=setTimeout(setTap,timeout);}
if(!this.in_doubletap){this.tap1=evt.xy;this.in_doubletap=true;}else{var center=this.center;this.tap2=evt.xy;this.in_doubletap=false;var args=[evt,this.tap2,this.tap1];this.callback('doubletap',args);this.center=null;}}},CLASS_NAME:"IOL.Handler.DoubleTap"});IOL.Handler.Pinch=OpenLayers.Class(OpenLayers.Handler,{scale:1,center:null,touchmove:function(evt){if(evt.touches.length==2){this.center=this._get_center(evt);}},gesturechange:function(evt){this.callback("change",[evt]);},_get_center:function(evt){var x=(evt.touches[0].clientX+evt.touches[1].clientX)/2;var y=(evt.touches[0].clientY+evt.touches[1].clientY)/2;return new OpenLayers.Pixel(x,y);},gesturestart:function(evt){evt.preventDefault();this.scale=evt.scale;},gestureend:function(evt){evt.preventDefault();var scale=evt.scale;var dif=evt.scale-this.scale;var args=[evt,scale,dif,this.center];if(scale>1&&dif!=0){this.callback('dilate',args);}else{if(scale<1&&dif!=0){this.callback('pinch',args);}}
this.scale=scale;},CLASS_NAME:"IOL.Handler.Pinch"});IOL.Control.TouchZoom=OpenLayers.Class(OpenLayers.Control,{doubleTapClass:IOL.Handler.DoubleTap,pinchClass:IOL.Handler.Pinch,doubleTapHandler:null,pinchHandler:null,zoom:"out",tapZoomInOnly:true,tapZoom:function(evt,center){var out="out";if(this.zoom==null||this.tapZoomInOnly||this.zoom==out){this.map.zoomIn();this.zoom="in";}else{this.map.zoomOut();this.zoom=out;}
this.centerMap(center);},initialize:function(options){this.handlers=[];OpenLayers.Control.prototype.initialize.apply(this,arguments);},activate:function(){for(var i=0;i<this.handlers.length;i++){this.handlers[i].activate();}
return OpenLayers.Control.prototype.activate.apply(this,arguments);},deactivate:function(){for(var i=0;i<this.handlers.length;i++){this.handlers[i].deactivate();}
return OpenLayers.Control.prototype.deactivate.apply(this,arguments);},centerMap:function(lonlat){if(IOL.isinstance(lonlat,OpenLayers.Pixel)){lonlat=this.map.getLonLatFromPixel(lonlat);}
this.map.setCenter(lonlat,this.map.getZoom());},dilateZoomIn:function(evt,scale,diff,center){this.centerMap(center);this.map.zoomIn();},changeZoom:function(evt){},pinchZoomOut:function(evt,scale,diff,center){if(this.limitZoomOut()==false){this.centerMap(center);this.map.zoomOut();}},draw:function(){if(this.doubleTapClass!=null){this.doubleTapHandler=new this.doubleTapClass(this,{doubletap:this.tapZoom});this.handlers.push(this.doubleTapHandler);}
if(this.pinchClass!=null){this.pinchHandler=new this.pinchClass(this,{change:this.changeZoom,dilate:this.dilateZoomIn,pinch:this.pinchZoomOut});this.handlers.push(this.pinchHandler);}},limitZoomOut:function(){if(this.map.getZoom()<=2){return true;}
return false;},CLASS_NAME:"IOL.Control.TouchZoom"});IOL.Control.Navigation=OpenLayers.Class(OpenLayers.Control.Navigation,{zoomWheelEnabled:false,dragPanClass:IOL.Control.DragPan,pinchZoomEnabled:true,touchZoomClass:IOL.Control.TouchZoom,initialize:function(options){this.handlers={};OpenLayers.Control.prototype.initialize.apply(this,arguments);},activate:function(){this.dragPan.activate();if(this.touchZoom!=null){this.touchZoom.activate();}
this.tap_handler=new IOL.Handler.Tap(this,{doubletap:this._dblclick,singletap:this._singleclick});this.tap_handler.activate();return OpenLayers.Control.prototype.activate.apply(this,arguments);},_dblclick:function(evt){var touch=evt.touches[0];OpenLayers.Event.stop(evt);IOL.fireMouseEvent("dblclick",this.map.div,touch);},_singleclick:function(evt){OpenLayers.Event.stop(evt);var touch=evt.touches[0];IOL.fireMouseEvent("click",this.map.div,touch);},deactivate:function(){this.dragPan.deactivate();this.tap_handler.deactivate();return OpenLayers.Control.prototype.deactivate.apply(this,arguments);},draw:function(){if(this.handleRightClicks){this.map.div.oncontextmenu=function(){return false;};}
this.dragPan=new this.dragPanClass(OpenLayers.Util.extend({map:this.map},this.dragPanOptions));this.touchZoom=new IOL.Control.TouchZoom({map:this.map});this.dragPan.draw();this.touchZoom.draw();this.activate();},dilate:function(evt){this.map.zoomIn();},pinch:function(evt){if(this.limitZoomOut()==false){this.map.zoomOut();}},limitZoomOut:function(){if(this.map.getZoom()<=2){return true;}
return false;},CLASS_NAME:"IOL.Control.Navigation"});IOL.Handler.Tap=OpenLayers.Class(OpenLayers.Handler,{singletap_timer:false,singletap_timeout:310,doubletap_timeout:300,doubletap_timer:false,in_doubletap:false,in_singletap:false,fire_single:false,touchstart:function(evt){var timeout=this.doubletap_timeout;if(!this.singletap_timer&&!this.doubletap_timer){var obj=this;function reset(){obj.in_singletap=false;obj.singletap_timer=false;obj.fire_single=true;}
this.singletap_timer=setTimeout(reset,this.singletap_timeout);}
if(event.touches.length==1){if(!this.doubletap_timer){var obj=this;function reset(){obj.in_doubletap=false;obj.doubletap_timer=false;obj.in_singletap=false;obj.singletap_timer=false;}
this.doubletap_timer=setTimeout(reset,this.doubletap_timeout);}}},touchmove:function(evt){this.clear_flags();},clear_flags:function(evt){this.in_doubletap=false;this.doubletap_timer=false;this.in_singletap=false;this.singletap_timer=false;this.fire_single=false;this.center=null;},touchend:function(evt){var obj=this;if(evt.touches.length==1){if(!this.in_doubletap){this.tap1=evt.xy;this.in_doubletap=true;var args=[evt,this.tap1];function fire(){if(this.fire_single){obj.callback('singletap',args);this.clear_flags();}};setTimeout(300,fire);}else{var center=this.center;this.tap2=evt.xy;this.clear_flags();var args=[evt,this.tap2,this.tap1];this.callback('doubletap',args);this.center=null;}}},CLASS_NAME:"IOL.Handler.Tap"});IOL.Handler.Feature=OpenLayers.Class(OpenLayers.Handler.Feature,{EVENTMAP:{'click':{'in':'click','out':'clickout'},'touchmove':{'in':'over','out':'out'},'dblclick':{'in':'dblclick','out':null},'touchstart':{'in':null,'out':null},'touchend':{'in':null,'out':null}},touchstart:function(evt){this.down=evt.xy;return this.handle(evt)?!this.stopDown:true;},touchend:function(evt){this.up=evt.xy;return this.handle(evt)?!this.stopUp:true;},click:function(evt){return this.handle(evt)?!this.stopClick:true;},touchmove:function(evt){if(!this.callbacks['over']&&!this.callbacks['out']){return true;}
this.handle(evt);return true;},dblclick:function(evt){return!this.handle(evt);},CLASS_NAME:"IOL.Handler.Feature"});IOL.Control.DragFeature=OpenLayers.Class(OpenLayers.Control.DragFeature,{dragClass:IOL.Handler.Drag,featureClass:IOL.Handler.Feature,initialize:function(layer,options){OpenLayers.Control.prototype.initialize.apply(this,[options]);this.layer=layer;this.handlers={drag:new this.dragClass(this,OpenLayers.Util.extend({down:this.downFeature,move:this.moveFeature,up:this.upFeature,out:this.cancel,done:this.doneDragging},this.dragCallbacks)),feature:new this.featureClass(this,this.layer,OpenLayers.Util.extend({over:this.overFeature,out:this.outFeature},this.featureCallbacks),{geometryTypes:this.geometryTypes})};},CLASS_NAME:"IOL.Control.DragFeature"});IOL.Handler.Point=OpenLayers.Class(OpenLayers.Handler.Point,{mousedown:null,touchstart:function(evt){evt.preventDefault();if(this.lastDown&&this.lastDown.equals(evt.xy)){return true;}
if(this.lastDown==null){if(this.persist){this.destroyFeature();}
this.createFeature();}
this.lastDown=evt.xy;this.drawing=true;var lonlat=this.map.getLonLatFromPixel(evt.xy);this.point.geometry.x=lonlat.lon;this.point.geometry.y=lonlat.lat;this.point.geometry.clearBounds();this.drawFeature();return false;},touchmove:function(evt){if(this.drawing){evt.preventDefault();var lonlat=this.map.getLonLatFromPixel(evt.xy);this.point.geometry.x=lonlat.lon;this.point.geometry.y=lonlat.lat;this.point.geometry.clearBounds();this.drawFeature();}
return true;},touchend:function(evt){if(this.drawing){this.finalize();return false;}else{return true;}},CLASS_NAME:"IOL.Handler.Point"});IOL.Handler.Path=OpenLayers.Class(OpenLayers.Handler.Path,{delay:300,lastTime:null,mousedown:null,touchstart:function(evt){evt.preventDefault();if(this.lastDown&&this.lastDown.equals(evt.xy)){return false;}
if(this.lastDown==null){if(this.persist){this.destroyFeature();}
this.createFeature();}
this.mouseDown=true;this.lastDown=evt.xy;var lonlat=this.control.map.getLonLatFromPixel(evt.xy);this.point.geometry.x=lonlat.lon;this.point.geometry.y=lonlat.lat;this.point.geometry.clearBounds();if((this.lastUp==null)||!this.lastUp.equals(evt.xy)){this.addPoint();}
this.drawFeature();this.drawing=true;return false;},touchmove:function(evt){if(this.drawing){var lonlat=this.map.getLonLatFromPixel(evt.xy);this.point.geometry.x=lonlat.lon;this.point.geometry.y=lonlat.lat;this.point.geometry.clearBounds();if(this.mouseDown&&this.freehandMode(evt)){this.addPoint();}else{this.modifyFeature();}
this.drawFeature();}
return true;},touchend:function(evt){this.mouseDown=false;if(this.drawing){if(this.freehandMode(evt)){if(this.persist){this.destroyPoint();}
this.finalize();}else{this.lastUp=evt.xy;if(this.lastUp==null){this.addPoint();}
var t=(new Date).getTime();var doubleTap=this.lastTime&&(t-this.lastTime)<this.delay;if(doubleTap){if(this.persist){this.destroyPoint();}
this.finalize();}else{this.lastTime=t;}}
return false;}
return true;},CLASS_NAME:"IOL.Handler.Path"});IOL.Handler.Polygon=OpenLayers.Class(IOL.Handler.Path,OpenLayers.Handler.Polygon,{CLASS_NAME:"IOL.Handler.Polygon"});